import { Product } from './types/Product'

export const sampleProducts: Product[] = [
  {
    name: 'Nike slim shirt',
    slug: 'nike-slim-shirt',
    category: 'shirts',
    image: '../images/p1.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'Long sleeved nike shirt',
  },
  {
    name: 'Adidas Fit Shirt',
    slug: 'adidas-fit-shirt',
    category: 'shirts',
    image: '../images/p2.jpg',
    price: 100,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'Addidas shirt',
  },
  {
    name: 'Lacoste Free Pants',
    slug: 'lacoste-free-pants',
    category: 'pants',
    image: '../images/p3.jpg',
    price: 220,
    countInStock: 0,
    brand: 'Lacoste',
    rating: 4.8,
    numReviews: 17,
    description: 'Lacoste pants',
  },
  {
    name: 'Nike Slim Pants',
    slug: 'nike-slim-pants',
    category: 'pants',
    image: '../images/p4.jpg',
    price: 80,
    countInStock: 15,
    brand: 'Nike',
    rating: 4.8,
    numReviews: 17,
    description: 'Nike pants',
  },
]
